#!/usr/bin/env bash
# VoiceBeacon Node Setup Script
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
SERVICE_NAME="voicebeacon"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; BOLD='\033[1m'; NC='\033[0m'
info()    { echo -e "${BLUE}>> $*${NC}"; }
success() { echo -e "${GREEN}OK $*${NC}"; }
warn()    { echo -e "${YELLOW}!! $*${NC}"; }
die()     { echo -e "${RED}!! $*${NC}" >&2; exit 1; }

echo ""
echo -e "${BOLD}VoiceBeacon Node -- Setup${NC}"
echo ""

# 1. System packages
info "Installing system packages (rtl-sdr, sox, python3-pip)..."
sudo apt-get install -y rtl-sdr sox python3-pip

# 2. Python packages
echo ""
info "Installing Python packages..."
pip3 install -r "$SCRIPT_DIR/requirements.txt" --break-system-packages -q
success "Python packages installed."

# helper called later if user picks usb/lsb mode
install_csdr() {
    echo ""
    info "SSB mode requires csdr. Attempting to install..."
    if sudo apt-get install -y csdr 2>/dev/null; then
        success "csdr installed via apt."
        return
    fi
    warn "csdr not in apt repos. Building from source (requires ~5 min)..."
    if ! command -v cmake &>/dev/null; then
        sudo apt-get install -y cmake libfftw3-dev
    fi
    CSDR_TMP="$(mktemp -d)"
    git clone --depth 1 https://github.com/ha7ilm/csdr.git "$CSDR_TMP/csdr"
    cmake -S "$CSDR_TMP/csdr" -B "$CSDR_TMP/build" -DCMAKE_BUILD_TYPE=Release
    make -C "$CSDR_TMP/build" -j"$(nproc)"
    sudo make -C "$CSDR_TMP/build" install
    rm -rf "$CSDR_TMP"
    success "csdr built and installed."
}

# 3. .env check
echo ""
SKIP_ENV=false
if [[ -f "$ENV_FILE" ]]; then
    warn "A .env already exists at $ENV_FILE"
    read -rp "Overwrite it? [y/N] " _ow
    [[ "$_ow" =~ ^[Yy]$ ]] || SKIP_ENV=true
fi

if [[ "$SKIP_ENV" == "false" ]]; then

    # 4. SDR hardware
    echo ""
    echo -e "${BOLD}SDR Hardware${NC}"
    echo "  1) Nooelec NESDR SMArt v5 (R820T2)"
    echo "  2) RTL-SDR Blog V4        (R828D)"
    echo "  3) Other RTL2832U dongle"
    read -rp "Select [1-3, default 1]: " _sdr
    _sdr="${_sdr:-1}"
    case "$_sdr" in
        2) SDR_MODEL="RTL-SDR Blog V4"
           echo ""
           warn "V4 may need special drivers -- see https://www.rtl-sdr.com/V4/"
           warn "If rtl_test fails: sudo apt-get purge rtl-sdr && sudo apt-get install rtl-sdr-blog" ;;
        3) SDR_MODEL="RTL2832U SDR" ;;
        *) SDR_MODEL="Nooelec NESDR SMArt v5" ;;
    esac

    # 5. Receiver settings
    echo ""
    echo -e "${BOLD}Receiver Configuration${NC}"
    echo "  Frequency examples: 145.150M (2m FM)  14.225M (20m USB)  3.900M (75m AM)"
    read -rp "  Frequency to monitor: " RECV_FREQ
    [[ -n "$RECV_FREQ" ]] || die "Frequency is required."

    echo "  Modes: fm  am  usb  lsb"
    read -rp "  Demodulation mode [fm]: " RECV_MODE
    RECV_MODE="${RECV_MODE:-fm}"
    if [[ "$RECV_MODE" == "usb" || "$RECV_MODE" == "lsb" ]]; then
        install_csdr
    fi

    echo "  Lower gain = less compression for nearby stations; higher = more sensitivity"
    read -rp "  SDR gain in dB [10]: " RECV_GAIN
    RECV_GAIN="${RECV_GAIN:-10}"

    echo "  Debug mode saves a WAV recording of every transcribed chunk to recordings/"
    read -rp "  Enable debug mode? [y/N] " _debug
    RECV_DEBUG="false"
    [[ "$_debug" =~ ^[Yy]$ ]] && RECV_DEBUG="true"

    # 6. Credentials
    echo ""
    echo -e "${BOLD}API Credentials${NC}"
    read -rp "  OpenAI API key (sk-...): " OPENAI_KEY
    [[ -n "$OPENAI_KEY" ]] || warn "No OpenAI key -- transcription will fail at runtime."
    read -rp "  VoiceBeacon node token (from admin, leave blank if none): " NODE_TOKEN

    # 7. Write .env
    echo ""
    info "Writing $ENV_FILE..."
    cat > "$ENV_FILE" <<ENVEOF
# VoiceBeacon Node Configuration -- generated by setup.sh $(date)
# SDR hardware: $SDR_MODEL

OPENAI_API_KEY=$OPENAI_KEY
VOICEBEACON_NODE1_TOKEN=$NODE_TOKEN
VOICEBEACON_API_URL=https://voicebeacon-api.fly.dev

# Receiver defaults (read by receiver.py when no CLI flags given)
VOICEBEACON_FREQ=$RECV_FREQ
VOICEBEACON_MODE=$RECV_MODE
VOICEBEACON_GAIN=$RECV_GAIN
VOICEBEACON_DEVICE=0
VOICEBEACON_DEBUG=$RECV_DEBUG
ENVEOF
    success ".env written."
fi

# 8. Startup service
echo ""
echo -e "${BOLD}Startup Service${NC}"
echo "  Creates a systemd service that runs receiver.py on every boot."
echo "  Frequency/mode/gain are read from .env -- edit that file to change them."
read -rp "  Run VoiceBeacon on boot? [y/N] " _boot

if [[ "$_boot" =~ ^[Yy]$ ]]; then
    CURRENT_USER="$(whoami)"
    PYTHON_BIN="$(command -v python3)"
    echo ""
    info "Creating $SERVICE_FILE..."
    sudo tee "$SERVICE_FILE" > /dev/null <<SVCEOF
[Unit]
Description=VoiceBeacon SDR Node
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$CURRENT_USER
WorkingDirectory=$SCRIPT_DIR
EnvironmentFile=$ENV_FILE
ExecStart=$PYTHON_BIN $SCRIPT_DIR/receiver.py
Restart=always
RestartSec=15
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
SVCEOF
    sudo systemctl daemon-reload
    sudo systemctl enable "$SERVICE_NAME"
    success "Service enabled -- will start on next boot."
    echo ""
    echo "  sudo systemctl start $SERVICE_NAME       # start now"
    echo "  sudo journalctl -u $SERVICE_NAME -f      # follow logs"
    echo "  sudo systemctl stop $SERVICE_NAME        # stop"
    echo "  sudo systemctl disable $SERVICE_NAME     # remove from boot"
fi

# 9. SDR check
echo ""
info "Checking SDR connection..."
if lsusb 2>/dev/null | grep -qi "realtek\|2838\|2832"; then
    SDR_USB="$(lsusb | grep -i 'realtek\|2838\|2832' | head -1)"
    success "SDR detected: $SDR_USB"
else
    warn "No Realtek USB device found. Check the USB connection, then run: rtl_test"
    echo "  Tip: sudo rmmod dvb_usb_rtl28xxu  (unload conflicting kernel module)"
fi

# 10. Done
echo ""
echo -e "${GREEN}${BOLD}Setup complete!${NC}"
echo ""
FREQ_HINT="${RECV_FREQ:-<freq>}"
MODE_HINT="${RECV_MODE:-fm}"
echo "  Manual run:  python3 $SCRIPT_DIR/receiver.py"
echo "  Diagnose:    python3 $SCRIPT_DIR/diagnose.py --freq $FREQ_HINT"
[[ "${_boot:-n}" =~ ^[Yy]$ ]] && echo "  Start now:   sudo systemctl start $SERVICE_NAME"
echo "  Full guide:  $SCRIPT_DIR/SETUP.md"
echo ""
